### ISSUE TITLE
Install error on julia 1.3.1

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGraphics/Immerse.jl#81]
Hi, I got this error trying to install on julia 1.3.1:

(v1.3) pkg> add Immerse
  Updating registry at `C:\Users\Kelvyn\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Immerse [2a4eff87]:
 Immerse [2a4eff87] log:
 ├─possible versions are: [0.1.0-0.1.1, 1.0.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 1.0.0]
 ├─restricted by compatibility requirements with FixedPointNumbers [53c48c17] to versions: 0.1.0-0.1.1 or uninstalled, leaving only versions: 0.1.0-0.1.1
 │ └─FixedPointNumbers [53c48c17] log:
 │   ├─possible versions are: [0.5.0-0.5.3, 0.6.0-0.6.1, 0.7.0-0.7.1] or uninstalled
 │   └─restricted to versions 0.6.1 by an explicit requirement, leaving only versions 0.6.1
 └─restricted by compatibility requirements with Gtk [4c0ca9eb] to versions: 1.0.0 or uninstalled — no versions left
   └─Gtk [4c0ca9eb] log:
     ├─possible versions are: [0.16.0-0.16.5, 0.17.0, 0.18.0, 1.0.0, 1.1.0-1.1.2] or uninstalled
     └─restricted to versions 1.1.2 by an explicit requirement, leaving only versions 1.1.2

**Comment by jonathanBieler** [comment]
If I understand correctly you have another package that require FixedPointNumbers to be version 0.6.1 ("restricted to versions 0.6.1 by an explicit requirement"), while I require 0.7.0 in Immerse. 

I could try to loosen the bound on FixedPointNumbers, I think it should work. Otherwise we should figure out which package require 0.6.1 and update it. What do you have in your environment ? `]st`

In the meantime you can also try to dev the package `]dev Immerse`, that sometimes just work.

**Comment by jonathanBieler** [comment]
I've relaxed the bounds to v0.6.1, you can try `add GtkUtilities#master` and `add Immerse#master` to see if that helps.

**Comment by Kelvyn88** [comment]
Thanks, it is working now.
